export enum MapType {
    REPERTOIRE = 'REPERTOIRE',
    PAGE_INFORMATION_ALBUM = 'ALBUM_FAMILLE',
    PAGE_INFORMATION_INDEX_VOLETA = 'INDEXE_VOLET_A',
    PAGE_INFORMATION_INDEX_VOLETB = 'INDEXE_VOLET_b',
    FOURNISSEURS = 'FOURNISSEURS',
}
